version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
