version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Paris
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Paris
  commit-message:
    prefix: ci
    include: scope
