---

language: go
go:
  - 1.17.x
  - master
env:
  global:
    - GO111MODULE=on
    - GOOS=linux
  jobs:
    - GOARCH=amd64
    - GOARCH=arm64
    - GOARCH=386
after_success:
  bash <(curl -s https://codecov.io/bash)

jobs:
  allow_failures:
    - go: master

notifications:
  email: false
